my_string=input('Введите № домашнего задания: ')
list_a= ("Введите № домашнего задания:")
number_my_string = len(list_a)
print("Number_my_simbol:", number_my_string)
my_string=('Введите № домашнего задания:')
print('Введите № домашнего задания:'.upper())
print('Введите № домашнего задания:'.lower())
print('Введите № домашнего задания:'.replace(' ',''))
print(my_string[0])
print(my_string[27])